name: my_project_name
description: "A Netflix clone app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  video_player: ^2.8.2
  chewie: ^1.7.5
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  wakelock_plus: ^1.1.4
  package_info_plus: ^5.0.1
  share_plus: ^7.2.2
  url_launcher: ^6.2.4
  xml: ^6.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
